# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/eight_bit_kicking_image/eight_bit_kicking_image.xci
# IP: The module: 'eight_bit_kicking_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/eight_bit_kicking_image/eight_bit_kicking_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eight_bit_kicking_image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/eight_bit_kicking_image/eight_bit_kicking_image.xci
# IP: The module: 'eight_bit_kicking_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/eight_bit_kicking_image/eight_bit_kicking_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eight_bit_kicking_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
