# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final.xci
# IP: The module: 'clk_wiz_final' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_final'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_final'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_final'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final.xci
# IP: The module: 'clk_wiz_final' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_final'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_final'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/athena.mit.edu/user/d/i/dianah13/ddl/6.111/final_project/final_project.srcs/sources_1/ip/clk_wiz_final/clk_wiz_final_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_final'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
